### ISSUE TITLE
Thanks for your great blog and code samples.

### ISSUE THREAD

**Issue by 690130229** [SilentAlice/BlogExamples#1]
仅仅为了表达感谢，我最近在学xen相关的，一直苦于找不到相关的资料，偶然发现你的blog，并且还提供了详细的code，真是喜出望外呀。再次表示感谢。

**Comment by SilentAlice** [comment]
@690130229 我也是小白:) 现在也是被这东东搞得焦头烂额..还有一堆不懂的东西，共勉~  有什么问题可以交流吖

**Comment by 690130229** [comment]
@SilentAlice 好的，有问题欢迎一起讨论呀，你的gmail邮箱是真实的吗？

**Comment by SilentAlice** [comment]
@690130229 Yeah, it's real. I will close this issue and further message can be sent via emails :) yumingwu233@gmail.com
